# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				trapped_chest = true
				blast_furnace = true

			[light_sources.settings.block_entities.blockus]
				wooden_barrel = true

			[light_sources.settings.block_entities.rocks]
				overworld_geyser_blockentity = true
				nether_geyser_blockentity = true

			[light_sources.settings.block_entities.ducts]
				duct = true

			[light_sources.settings.block_entities.toms_storage]

				[light_sources.settings.block_entities.toms_storage.ts]

					[light_sources.settings.block_entities.toms_storage.ts.storage_terminal]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.level_emitter]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_cable_connector_filtered]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.painted]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_cable_connector]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventoty_hopper_basic]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.crafting_terminal]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_proxy]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.inventory_connector]
						tile = true

					[light_sources.settings.block_entities.toms_storage.ts.open_crate]
						tile = true

			[light_sources.settings.block_entities.bedspreads]
				decorated_bed = true

			[light_sources.settings.block_entities.adorn]
				drawer = true
				kitchen_cupboard = true
				trading_station = true
				shelf = true

			[light_sources.settings.block_entities.comforts]
				sleeping_bag = true
				hammock = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true

			[light_sources.settings.entities.unvotedandshelved]
				glare = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.biomemakeover]
				decayed = true
				dragonfly = true
				lightning_bug = true
				toad = true
				lightning_bug_alternate = true

			[light_sources.settings.entities.throwabletorch]
				throwable_magma_torch = true
				throwable_clay_torch = true
				throwable_honeycomb_torch = true
				throwable_slime_torch = true

			[light_sources.settings.entities.ottercraft]
				otter = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.betternether]
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				skull = true
				naga = true

			[light_sources.settings.entities.guardiansgalore]
				bear = true

			[light_sources.settings.entities.ecologics]
				coconut_crab = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.wilderworld]
				butterfly = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true

			[light_sources.settings.entities.boatcontainer]
				chest_boat = true

			[light_sources.settings.entities.llamarama]
				bumble_llama = true
				caravan_trader = true
				mossy_llama = true
				woolly_llama = true

			[light_sources.settings.entities.sit]
				entity_sit = true

			[light_sources.settings.entities.wildlife]
				snail = true
				rhino_beetle = true
				spicebush_butterfly = true
				possum = true
				ladybug = true
				morpho_butterfly = true
				dragonfly = true
				robin = true
				hermitcrab = true
				iguana = true
				king_snake = true
				staghorn_beetle = true
				armadillo = true
				glasswing_butterfly = true
				sparrow = true
				lark = true
				tiger_butterfly = true
				beaver = true
				phoebe = true
				june_beetle = true
				python = true
				chameleon = true
				swallow = true
				flycatcher = true
				ant = true
				monarch_butterfly = true
				stickbug = true
				milk_snake = true
				bluebird = true
				sunflowerbeetle = true
				badger = true
				goldfinch = true
				wren = true
				gecko = true
				hedgehog = true
				cricket = true
				ferret = true
				white_eye = true
				spider = true
				crab = true

